
project: 
  type: website
  render:
    - "*.{qmd,R,py}"
    - "!utils.py"
  preview:
    browser: true
    
website:
  title: "Kiara Koli"
  site-url: "https://kiara-koli.netlify.app/"
  description: "Hi my friends. Let's connect."
  twitter-card: true
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        href: https://github.com
      - icon: linkedin
        href: https://linkedin.com
      - icon: facebook
        href: https://facebook.com
      - icon: instagram
        href: https://instagram.com  
  page-footer: 
    left: "Copyright 2025, kiara koli" 
    center: "Made with ❤️"
    right: "Supported by [SARA](https://sara-edu.netlify.app/)"
      
        
format:
  html:
    theme: sketchy
    css: styles.css
    fontcolor: black
    linkcolor: navy
    backgroundcolor: gold
    fontsize: 18px
    
    
    