
project: 
  type: website
  preview:
    browser: true
    
website:
  title: "Kiara Koli"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
        
format:
  html:
    theme: sketchy
    fontcolor: black
    linkcolor: navy
    backgroundcolor: gold
    fontsize: 25px
    
    
    